packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  'esbuild': true
  'unrs-resolver': true

minimumReleaseAgeExclude:
  - '@jest/console@30.5.2'
  - '@jest/core@30.5.2'
  - '@jest/environment@30.5.2'
  - '@jest/expect-utils@30.5.2'
  - '@jest/expect@30.5.2'
  - '@jest/fake-timers@30.5.2'
  - '@jest/globals@30.5.2'
  - '@jest/reporters@30.5.2'
  - '@jest/source-map@30.5.2'
  - '@jest/test-result@30.5.2'
  - '@jest/test-sequencer@30.5.2'
  - '@jest/transform@30.5.2'
  - babel-jest@30.5.2
  - expect@30.5.2
  - jest-circus@30.5.2
  - jest-cli@30.5.2
  - jest-config@30.5.2
  - jest-diff@30.5.2
  - jest-each@30.5.2
  - jest-environment-node@30.5.2
  - jest-matcher-utils@30.5.2
  - jest-mock@30.5.2
  - jest-resolve-dependencies@30.5.2
  - jest-runner@30.5.2
  - jest-runtime@30.5.2
  - jest-snapshot@30.5.2
  - jest-watcher@30.5.2
  - jest@30.5.2
