const _ = require('lodash')
const cssMatcher = require('jest-matcher-css')
const postcss = require('postcss')
const tailwindcss = require('tailwindcss')

/**
 * generatePluginCss
 * Handles generating base tailwind css
 * @param {*} config
 * @param {object} pluginOptions are the options passed to the plugin
 * @return
 */
const generatePluginCss = (config, pluginOptions = {}) => {
  return postcss(
    tailwindcss(
      _.merge(
        {
          theme: {
            extend: {
              color: {}
            }
          },
          variants: [],
          plugins: [require('./index.js')(pluginOptions)],
        },
        config
      )
    )
  )
    .process('@tailwind components; @tailwind utilities', {
      from: undefined,
    })
    .then((result) => {
      // console.log('results', result.css)
      return result.css
    })
}

/**
 * Base display classes from TailwindCSS
 * Note: I can't figure out how to get around these. If display
 *       is not added above to corePlugins, nothing shows up
 */
const baseCss = `
`

expect.extend({
  toMatchCss: cssMatcher,
})

test('color are generated by default', () => {
  return generatePluginCss(null, { extend: {} }).then((css) => {
    expect(css).toMatch(/(clrs-navy)/)
  })
})

test('colors with alpha are generated by default', () => {
  return generatePluginCss(null, { extend: {} }).then((css) => {
    expect(css).toMatch(/(clrs-navy-a50)/)
  })
})

